// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDbCUtT95zlsI2YqhL9UeCc4aacj7fDekI',
    appId: '1:690751168321:web:3fc71e8abb77876b0acbc0',
    messagingSenderId: '690751168321',
    projectId: 'pemrogramanmobilelanjut-14892',
    authDomain: 'pemrogramanmobilelanjut-14892.firebaseapp.com',
    databaseURL: 'https://pemrogramanmobilelanjut-14892-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'pemrogramanmobilelanjut-14892.firebasestorage.app',
    measurementId: 'G-6F12RCHZ52',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCx9U3mYyWTEyeYa_nnD9v4VeOAzEDeoR4',
    appId: '1:690751168321:android:53aea6e96cf2f6560acbc0',
    messagingSenderId: '690751168321',
    projectId: 'pemrogramanmobilelanjut-14892',
    databaseURL: 'https://pemrogramanmobilelanjut-14892-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'pemrogramanmobilelanjut-14892.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDs7956GiUIZ3Ztl4xVURkYOXO8v6oVwHU',
    appId: '1:690751168321:ios:16c7d434b516e4b90acbc0',
    messagingSenderId: '690751168321',
    projectId: 'pemrogramanmobilelanjut-14892',
    databaseURL: 'https://pemrogramanmobilelanjut-14892-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'pemrogramanmobilelanjut-14892.firebasestorage.app',
    iosClientId: '690751168321-calirvjlislfitopsl1c2me589hom4jo.apps.googleusercontent.com',
    iosBundleId: 'com.example.apkSukorame',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDs7956GiUIZ3Ztl4xVURkYOXO8v6oVwHU',
    appId: '1:690751168321:ios:16c7d434b516e4b90acbc0',
    messagingSenderId: '690751168321',
    projectId: 'pemrogramanmobilelanjut-14892',
    databaseURL: 'https://pemrogramanmobilelanjut-14892-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'pemrogramanmobilelanjut-14892.firebasestorage.app',
    iosClientId: '690751168321-calirvjlislfitopsl1c2me589hom4jo.apps.googleusercontent.com',
    iosBundleId: 'com.example.apkSukorame',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDbCUtT95zlsI2YqhL9UeCc4aacj7fDekI',
    appId: '1:690751168321:web:8c034e833e0486fc0acbc0',
    messagingSenderId: '690751168321',
    projectId: 'pemrogramanmobilelanjut-14892',
    authDomain: 'pemrogramanmobilelanjut-14892.firebaseapp.com',
    databaseURL: 'https://pemrogramanmobilelanjut-14892-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'pemrogramanmobilelanjut-14892.firebasestorage.app',
    measurementId: 'G-K2TK2SLXNJ',
  );

}